### ISSUE TITLE
Remove dependence on existing path /var/lib/nova /var/lib/libvirt on host.

### ISSUE THREAD

**Issue by DTadrzak** [stackanetes/stackanetes#10]
Currently, manifests require  created dirs  like /var/lib/nova and /var/lib/libvirt on hosts to run a pod.

**Comment by ant31** [comment]
This dirs are created on each nodes by the daemonset `network-node`

```yaml
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: network-node
spec:
  template:
    metadata:
      labels:
        app: network-node
      name: network-node
    spec:
      volumes:
        - name: lib-modules
          hostPath:
            path: /lib/modules
        - name: var-lib-nova
          hostPath:
            path: /var/lib/nova
        - name: var-lib-libvirt
          hostPath:
            path: /var/lib/libvirt
```

I tryied to deploy stackanetes without manually create this directories and they have been created as expected. 

I think this ticket can be closed
