### ISSUE TITLE
Remove hardcoded  path to resolv.conf in nova-compute.yml and network-node.yml.

### ISSUE THREAD

**Issue by PiotrProkop** [stackanetes/stackanetes#9]
Currently compute-nodes and network-nodes resolv.conf with cluster dns address is mounted from hardcoded local path.

**Comment by ant31** [comment]
We can create a configmap instead of using hostpath. 

[configmap](https://github.com/kubespray/kpm-stackanetes/blob/master/configuration/templates/resolv-configmap.yaml)
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: openstack-resolvconf
data:
  resolv.conf: |-
    search {{namespace}}.svc.cluster.local svc.cluster.local cluster.local
    nameserver {{dns_server}}
    options ndots:5
```

and then use this configmap:

[network-node-ds.yaml](https://github.com/kubespray/kpm-stackanetes/blob/master/network/templates/network-node-ds.yaml):
```
      volumes:
        - name: resolv
          configMap:
            name: openstack-resolvconf
            items:
              - key: resolv.conf
                path: resolv.conf
```

**Comment by PiotrProkop** [comment]
Yeah, thanks :+1:

**Comment by ant31** [comment]
I've just noticed that we can't map a single file in an existing directory, it will mount the volume. 
So I mount the configmap to another path that /etc, and then copy the `resolv.conf`

```yaml
         volumeMounts:
            - mountPath: /etc/resolv  # non-existing directory
              name: resolv            # name of the configmap
          lifecycle:
            postStart:
              exec:
                command:              # 'copy' of the resolv.conf                        
                  - "cp"
                  - "/etc/resolv/resolv.conf"
                  - "/etc/resolv.conf"
```

It's a little bit 'hacky' but, I think less than having hardcoded path on the host, and it does't require any manual action from users.
